"""krw_balance_snapshots

Revision ID: 3809839a7833
Revises: 864cc14109bd
Create Date: 2026-05-26 17:30:14.576671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3809839a7833'
down_revision: Union[str, None] = '864cc14109bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('krw_balance_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('amount_krw', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_krw_balance_date', 'krw_balance_snapshots', ['as_of_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_krw_balance_date', table_name='krw_balance_snapshots')
    op.drop_table('krw_balance_snapshots')
    # ### end Alembic commands ###
