"""initial schema

Revision ID: 47f3d940d6b8
Revises: 
Create Date: 2026-05-26 05:10:49.144269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47f3d940d6b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ath_state',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('ath_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('ath_date', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('fx_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usd_krw', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fx_ts_desc', 'fx_history', ['ts'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('holdings', sa.JSON(), nullable=False),
    sa.Column('total_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_krw', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_date')
    )
    op.create_table('prices_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'ts', name='uq_prices_symbol_ts')
    )
    op.create_index('ix_prices_symbol_ts_desc', 'prices_history', ['symbol', 'ts'], unique=False)
    op.create_table('rules_config',
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('alerts_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules_config.rule_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_rule_level_fired', 'alerts_log', ['rule_id', 'level', 'fired_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_rule_level_fired', table_name='alerts_log')
    op.drop_table('alerts_log')
    op.drop_table('rules_config')
    op.drop_index('ix_prices_symbol_ts_desc', table_name='prices_history')
    op.drop_table('prices_history')
    op.drop_table('portfolio_snapshots')
    op.drop_index('ix_fx_ts_desc', table_name='fx_history')
    op.drop_table('fx_history')
    op.drop_table('ath_state')
    # ### end Alembic commands ###
