"""tactical_deposits table

Revision ID: 864cc14109bd
Revises: e0c0a67a9124
Create Date: 2026-05-26 17:19:15.591839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '864cc14109bd'
down_revision: Union[str, None] = 'e0c0a67a9124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tactical_deposits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('deposit_date', sa.Date(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_krw', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tactical_deposits_date', 'tactical_deposits', ['deposit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tactical_deposits_date', table_name='tactical_deposits')
    op.drop_table('tactical_deposits')
    # ### end Alembic commands ###
