"""contributions and tactical_buys

Revision ID: e0c0a67a9124
Revises: 47f3d940d6b8
Create Date: 2026-05-26 16:15:11.571706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0c0a67a9124'
down_revision: Union[str, None] = '47f3d940d6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('amount_krw', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('core_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('core_krw', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('tactical_krw', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contributions_date', 'contributions', ['contribution_date'], unique=False)
    op.create_table('tactical_buys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('amount_krw', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rule_level', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tactical_buys_date', 'tactical_buys', ['buy_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tactical_buys_date', table_name='tactical_buys')
    op.drop_table('tactical_buys')
    op.drop_index('ix_contributions_date', table_name='contributions')
    op.drop_table('contributions')
    # ### end Alembic commands ###
